module.exports =
    'mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega' +
    'mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega' +
    'mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega' +
    'mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega' +
    'mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega' +
    'mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega' +
    'mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega' +
    'mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega' +
    'mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega' +
    'mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega' +
    'mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega' +
    'mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega' +
    'mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega' +
    'mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega' +
    'mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega' +
    'mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega' +
    'mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega' +
    'mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega' +
    'mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega' +
    'mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega' +
    'mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega' +
    'mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega' +
    'mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega' +
    'mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega' +
    'mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega' +
    'mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega' +
    'mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega' +
    'mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega' +
    'mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega' +
    'mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega' +
    'mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega' +
    'mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega' +
    'mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega' +
    'mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega' +
    'mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega' +
    'mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega' +
    'mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega' +
    'mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega' +
    'mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega' +
    'mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega' +
    'mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega' +
    'mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega' +
    'mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega' +
    'mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega' +
    'mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega' +
    'mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega' +
    'mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega' +
    'mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega' +
    'mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega' +
    'mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega' +
    'mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega' +
    'mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega' +
    'mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega' +
    'mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega' +
    'mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega' +
    'mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega mega';
